# cuando haga un on push
on: push
# correr un trabajo llamado deploy
name: deploy
job:
  deploy:
  # nombre
    name: deploy to cluster
    # runs-on: va a correr en el ultimo ubuntu a la moda pero con sopolte en una VM
    runs-on: ubuntu-latest
    # las acciones que vamos a recorrer
    steps:
    # acciones que estan en el repo
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}