on:
  push:
name: action
jobs:
  hello-world:
    name: un job para saludar
    runs-on: ubuntu-latest
    steps:
      - name: Step hola mundo
        id: hello
        uses: adrielmachado0111/test-hello-world-docker-actions@v2
        with:
          who-to-greet: "adriel"
      - name: Usar el output
        run: echo "La fecha fue {{ steps.hello.outputs.time }}"